#!/bin/bash

function checkGitRep(){
    log=`git log|grep fatal`
    if [[ $log == '' ]]; then
        return 1
    else
        return 0
    fi
}


function getGitBranch(){
    for i in `git branch`; do
        echo $i;
    done
}

getGitBranch
exit;

checkGitRep

if [[ $? == 0 ]]; then
    echo "不是一个git仓库!"
    exit
fi

exit

git checkout master && git pull && git checkout $1 && git merge master