#! /bin/sh

### BEGIN INIT INFO
# Provides:          mail_server
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts mail_server
# Description:       starts the mail push server daemon
### END INIT INFO

# 设置文件格式 ::set fileformat=unix

#php路径，如不知道在哪，可以用whereis php尝试
PHP_BIN=/usr//bin/php

#代码根目录
SERVER_PATH=/home/lerko/Documents/dev_12301/www/html/TerminalWebSocketServer

getMasterPid()
{
    PID=`/bin/ps axu|grep pft_http_server|grep server|grep running|awk '{print $2}'`
    echo $PID
}

getManagerPid()
{
    MID=`/bin/ps axu|grep pft_http_server|grep server|grep manager|awk '{print $2}'`
    echo $MID
}
case "$1" in
        start)
                PID=`getMasterPid`
                if [ -n "$PID" ]; then
                    echo -n "pft_http_server server is running"
                    exit 1
                fi
                echo -n "Starting pft_http_server server "
                nohup $PHP_BIN $SERVER_PATH/http.php default-httplocal > ~/swoole.log &
                echo " done"
        ;;

        stop)
                PID=`getMasterPid`
                if [ -z "$PID" ]; then
                    echo -n "pft_http_server server is not running"
                    exit 1
                fi
                echo -n "Gracefully shutting down pft_http_server server "

                kill $PID
                echo " done"
        ;;

        status)
                PID=`getMasterPid`
                if [ -n "$PID" ]; then
                    echo -n "pft_http_server server is running"
                else
                    echo -n "pft_http_server server is not running"
                fi
		ps -auxf|grep pft_http_server
        ;;

        force-quit)
                $0 stop
        ;;

        restart)
                $0 stop
                $0 start
        ;;

        reloadworker)
                MID=`getManagerPid`
                if [ -z "$MID" ]; then
                    echo -n "pft_http_server server is not running"
                    exit 1
                fi

                echo -n "Reload service mail_server "

                kill -USR1 $MID

                echo " done"
        ;;

        reloadtask)
                MID=`getManagerPid`
                if [ -z "$MID" ]; then
                    echo -n "pft_http_server server is not running"
                    exit 1
                fi

                echo -n "Reload service pft_http_server"

                kill -USR2 $MID

                echo " done"
        ;;

        reloadall)
                $0 reloadworker
                $0 reloadtask
        ;;

        *)
                echo "Usage: $0 {start|stop|force-quit|restart|reloadall/reloadworker/reloadtask|status}"
                exit 1
        ;;

esac
